# Lecture 2: Lists, Arrays, and Data Frames

## Today's Key Takeaways

- Create **lists**, **ndarrays**, and **data frames**: data structures that contain more than one item
- Extract **subsets** from and manipulate the shapes of these objects
- **Import** and **export** data from Excel

### Adding libraries to python

First we need to import the libraries that we'll want to use for today's class.

In [1]:
# Import required libraries
import numpy as np
import pandas as pd

# Setting pandas options
pd.set_option('display.precision', 2)
pd.set_option('display.max_columns',10)

## Lists

One of the most basic data structures available in Python for storing groups of things is the `list`. Lists can hold any type of data, and both their contents and their size.

In [2]:
mixedlist = [False,True,2,3,'Four','Five','Six']
print(mixedlist)

[False, True, 2, 3, 'Four', 'Five', 'Six']

### Subsetting

You can access subsets of this list by _slicing_.

In [3]:
# slicing out a single element.
mixedlist[1]

True

Note that to access the first element of `mixedlist` above, you must refer to it as the 0th index.

In [ ]:
# slicing out the first element.
mixedlist[0]

In [ ]:
# slicing a subset of elements.
mixedlist[1:4]

In [ ]:
# slicing a subset of elements using reverse numbering (from the end of the list).
mixedlist[-3:]

In [ ]:
# slicing a subset of elements from the beginning
mixedlist[4:]

In [ ]:
# slicing every third element
mixedlist[::3]

### <font color=brown> Practice </font>

1. Output the 4th through 6th elements of `mixedlist` (should yield a 3-element list)
2. Output the last two elements
3. Output the even elements

In [ ]:
mixedlist

### Changing the size and contents of lists

There are many different ways to adjust what lists contain:

Adding elements to lists

In [ ]:
print(mixedlist)

In [ ]:
# adding a single element to the end
mixedlist.append(6)
print(mixedlist)

In [4]:
# stitching two lists together
mixedlist + [1,2,3]

[False, True, 2, 3, 'Four', 'Five', 'Six', 1, 2, 3]

In [ ]:
# adding an element at a particular location
mixedlist.insert(6,2)
print(mixedlist)

#### Changing the contents of lists

You can change the contents of a list by setting slices of the list equal to your desired input.

In [5]:
print(mixedlist) #reminder of what mixedlist currently contains

[False, True, 2, 3, 'Four', 'Five', 'Six']

In [ ]:
# Changing the contents of a single element
mixedlist[1] = 1
print(mixedlist)

In [ ]:
# Changing the contents of multiple elements
mixedlist[-2:] = [5,6]

In [ ]:
print(mixedlist)

#### Removing elements from lists

You can remove specific elements that you don't want from lists, using either the `.remove()` method, or the `del()` function.

If you know which position, you want to remove, use `del`. The `del` function removes the element from a specific location (based on the slice that is input into the argument).

If you know what contents you want to remove (but not where it's located), use the `.remove()`. The `.remove()` will remove the first element in the list (from left to right) that matches the contents of the input argument.

In [ ]:
print(mixedlist) #reminder of what mixedlist currently contains

In [ ]:
# remove the second element
del(mixedlist[1])
print(mixedlist)

In [ ]:
# remove the first element that matches the contents of the input argument
mixedlist.remove(2)
print(mixedlist)

You can check the size of the list by using the function `len()`.

In [ ]:
len(mixedlist)

### Intersections and unions with `sets`
You might find it useful to tell what is in common to two lists (intersection), or what are the unique elements that are represented in both lists (union). One way of determining this us by using `sets`. Sets store unique elements, and can be used with the boolean/logical operator `&` (AND) to perform a set intersection and output the shared values between both lists. Using the `|` (OR) operator would give the union.

In [8]:
print(mixedlist) #reminder of what mixedlist currently contains

[False, True, 2, 3, 'Four', 'Five', 'Six']

In [10]:
secondList = [2,3,'ten',True]
print(secondList)

[2, 3, 'ten', True]

In [12]:
commonlist = list(set(mixedlist) & set(secondList)) #The "&" is the boolean/logical AND operator
print(commonlist)

[True, 2, 3]

In [13]:
unionlist = list(set(mixedlist) | set(secondList)) #The "|" is the boolean/logical OR operator
print(unionlist)

[False, True, 2, 3, 'Five', 'Six', 'ten', 'Four']

Notice that the ordering of the elements in `unionlist` is not the same as the input lists.

### Additional Reading:
[This website](https://www.tutorialspoint.com/python/python_lists.htm) and [this website](https://www.w3schools.com/python/python_lists.asp) give overviews of what you can do with lists. For advanced reading (optional), go [here](https://docs.python.org/3/tutorial/datastructures.html).

Note that you can include any basic data type in the same list.

## Using `numpy` and `pandas` to hold and manipulate data

While you can use lists to do some very basic data manipulation tasks, there are other data structures that in Python, including `numpy arrays` and `pandas data frames`, which both give a lot more flexibility and power to perform mathematical operations on the data contained in these objects.

`Numpy` introduces a new object for holding groups of variables: n-dimensional arrays of data (aka `ndarrays`).

After we introduce you to ndarrays we will switch to `pandas`, which is a wrapper for ndarrays that makes them much easier to use. Then we'll come back to `numpy` and show you some of the functions from `numpy` and `scipy`, which adds more complex mathematical and statistical functions to python.

### NumPy arrays: a new thing to hold other things

NumPy arrays (`ndarrays`) are essentially lists with two important restrictions:

 - An array can only hold **one** type of data
 - Arrays are somewhat unmutable:
     - you **can** change the contents of an ndarray
     - but you **can't** change the size or the data type of the array

Why would we want a list with extra restrictions? Speed, both in terms of time to compute and time to program.

The computer only needs to check the type of data once for the array, not once for each variable. This adds up when you have huge arrays like the results of an 'omics' experiment.

Being forced to organize your data makes it simpler to search, manipulate, and subset your data.

### Making a new `ndarray`
There are a number of ways to make `ndarrays`. You can import data from text files, convert a list to an `ndarray`, or with one of the `numpy` functions that builds basic `ndarray` types useful for data analysis.

In [3]:
# The `numpy` function arange(start, stop, step) gives you an array of values
# between the start and stop (not including the stop) incremented by step
# The default step is 1
array1 = np.array([1,2,3,4])

print(array1)

[1 2 3 4]

A key difference between ndarrays and lists is that mathematical operators work with differently. We'll demonstrate this by converting an ndarray to a list using `ndarray.tolist()` and performing the same operations on both.

In [7]:
#Convert a to a_list and then multiply both by two
a_list = array1.tolist()
print(array1)
print(a_list)
print(array1 * 2)
print(a_list * 2)

[1 2 3 4]
[1, 2, 3, 4]
[2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4]

Another key difference is that ndarrays can be made into any number of dimensions.

In [ ]:
# Now let's make a 2D array (in this case, a 4 x 2 array)
array2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(array2)

ndarray variables contain several "attributes" which describe the shape of the array:

In [ ]:
print(array2.size)  # number of elements
print(array2.ndim)  # number of dimensions
print(array2.shape) # number of elements per dimension (starts with rows, then columns)

### Subsetting

To extract subsets from arrays, you use the same slicing rules as for lists, and separate each dimension by using a "," sign:

In [ ]:
print(array2[:,1:3])

### Computation with `ndarrays`
`ndarrays` are particularly useful for performing math. Here's an example with summing.

In [4]:
print(array1) #reminder of contents of array1

[1 2 3 4]

In [12]:
array1multiply = np.multiply(array1,5) #multiply each element by 5
print(array1multiply)

[ 5 10 15 20]

In [22]:
arrayNeg = -1 * array1
print(arrayNeg)

[-1 -2 -3 -4]

In [23]:
absValue = np.abs(arrayNeg) #generates absolute value
print(absValue)

[1 2 3 4]

In [14]:
array1log2 = np.log2(array1) # take log transform
print(array1log2)

[0.        1.        1.5849625 2.       ]

You can also aggregate or accumulate mathematical calculations

In [8]:
array1sum = np.sum(array1) #summing the elements of array1 together
print(array1sum)

10

In [24]:
array1cumsum = np.cumsum(array1) #cumulative sum
print(array1cumsum)

[ 1  3  6 10]

The following table provides a list of useful aggregation functions available in `NumPy`:
|Function Name |	NaN-safe Version |	Description |
|--------------|-------------------|--------------|
|`np.sum` |	`np.nansum` |	Compute sum of elements |
|`np.prod` |	`np.nanprod`| 	Compute product of elements|
|`np.mean` | `np.nanmean`| 	Compute mean of elements|
|`np.std` | 	`np.nanstd` |	Compute standard deviation|
|`np.var` | `np.nanvar` |	Compute variance|
|`np.min` |	`np.nanmin` |	Find minimum value|
|`np.max` |	`np.nanmax` |	Find maximum value|
|`np.argmin` |	`np.nanargmin` |	Find index of minimum value|
|`np.argmax` |	`np.nanargmax` |	Find index of maximum value|
|`np.median` |	`np.nanmedian` |	Compute median of elements|
|`np.percentile`| `np.nanpercentile` |	Compute rank-based statistics of elements|
|`np.any` |	N/A | Evaluate whether any elements are true|
|`np.all` |	N/A |	Evaluate whether all elements are true|

### Additional Reading
[This website](https://jakevdp.github.io/PythonDataScienceHandbook/02.03-computation-on-arrays-ufuncs.html) gives more information about NumPy `ndarray` computation.

### Special types of `ndarrays`

There are some functions that can help you generate `ndarrays` pre-filled with specific types of numbers, like zeros, random numbers, etc.

In [16]:
IntegerRange = np.arange(1,5)
print(IntegerRange)

[1 2 3 4]

In [19]:
Zeroes = np.zeros(5)
print(Zeroes)

[0. 0. 0. 0. 0.]

In [26]:
RandomArray = np.random.rand(5)
print(RandomArray)

[0.8582489  0.71963765 0.71979274 0.75450408 0.66096503]

## Pandas data frames

`Pandas` takes `ndarrays` a step further, with additional functionalities, such as enabling direct import/export from other sources.

### Import data into a DataFrame
Let's import some data to work with.

`Pandas` provides simple tools for importing from Excel, csv, or any other common data format:
 - `read_csv`
 - `read_excel`
 - `read_clipboard`
 - `read_sql`

We'll start by importing a table of metadata using `pd.read_csv()`.

This dataset comes from an [RNAseq experiment comparing melanoma cell lines from 2017](https://www.nature.com/articles/s41467-017-02353-y) published in Nature Communications.

In [2]:
# Import comma-seperated data from a text file
df = pd.read_csv('~/LECTURE_MATERIALS/DataFiles/melanoma_CountsRaw.csv', index_col=0)

In [3]:
# Take a look at the contents of the variable df using df.head()
df.head()

,Sample_geo_accession,Stage,cell type,sample_number,cell_line,...,BP-2171C21.4,BP-2171C21.5,BP-2171C21.6,BP-2189O9.2,YR211F11.2
Sample Title,,,,,,,,,,,
FM_1,GSM2344965,primary melanocytes,normal melanocytes,1,FM,...,0,0,6,2,0
FM_2,GSM2344966,primary melanocytes,normal melanocytes,2,FM,...,0,0,0,4,0
FM_3,GSM2344967,primary melanocytes,normal melanocytes,3,FM,...,1,0,6,3,1
SK_MEL_28_1,GSM2344968,metastatic,melanoma cell line,4,SK_MEL_28,...,3,0,15,66,0
SK_MEL_28_2,GSM2344969,metastatic,melanoma cell line,5,SK_MEL_28,...,0,2,21,85,0

Pandas by default prefers to spreadsheet data organized such that individual samples/replicates are in represented in the rows, and different parameters/variables/properties are represented in the columns.

To take examine the data frame produced, `.shape` and `.head()` are useful:

In [4]:
# Data frames store information about their shape (i.e. numbers of rows and columns) in the .shape attribute.
df.shape

(12, 35243)

### Subsetting

One of the powerful features of data frames is that rows and columns can be referred to by names or numbers:

In [5]:
# Extracting data in all rows from the column named "Stage"
df['Stage']

Sample Title
FM_1            primary melanocytes
FM_2            primary melanocytes
FM_3            primary melanocytes
SK_MEL_28_1              metastatic
SK_MEL_28_2              metastatic
SK_MEL_28_3              metastatic
SK_MEL_147_1             metastatic
SK_MEL_147_2             metastatic
SK_MEL_147_3             metastatic
UACC_62_1                metastatic
UACC_62_2                metastatic
UACC_62_3                metastatic
Name: Stage, dtype: object

In [6]:
# Extracting data in all rows from the column named "Stage"
df.Stage

Sample Title
FM_1            primary melanocytes
FM_2            primary melanocytes
FM_3            primary melanocytes
SK_MEL_28_1              metastatic
SK_MEL_28_2              metastatic
SK_MEL_28_3              metastatic
SK_MEL_147_1             metastatic
SK_MEL_147_2             metastatic
SK_MEL_147_3             metastatic
UACC_62_1                metastatic
UACC_62_2                metastatic
UACC_62_3                metastatic
Name: Stage, dtype: object

In [7]:
# Extracting data in all columns from row "FM_1" (note that you need to add ".loc" in order to refer to the row names)
df.loc['FM_1']

Sample_geo_accession             GSM2344965
Stage                   primary melanocytes
cell type                normal melanocytes
sample_number                             1
cell_line                                FM
                               ...
BP-2171C21.4                              0
BP-2171C21.5                              0
BP-2171C21.6                              6
BP-2189O9.2                               2
YR211F11.2                                0
Name: FM_1, Length: 35243, dtype: object

To select multiple rows or columns, input a list:

In [8]:
df.loc[['FM_1','FM_2','FM_3'],'Stage']

Sample Title
FM_1    primary melanocytes
FM_2    primary melanocytes
FM_3    primary melanocytes
Name: Stage, dtype: object

You can also subset data by number by using "`.iloc`" (zero-indexing also applies here)

In [9]:
df.iloc[0:3,2]

Sample Title
FM_1    normal melanocytes
FM_2    normal melanocytes
FM_3    normal melanocytes
Name: cell type, dtype: object

To get Python to output the entire set of row and column names, you can use the `.index` and `.columns` attributes, respectively.

In [10]:
# listing the row names
df.index

Index(['FM_1', 'FM_2', 'FM_3', 'SK_MEL_28_1', 'SK_MEL_28_2', 'SK_MEL_28_3',
       'SK_MEL_147_1', 'SK_MEL_147_2', 'SK_MEL_147_3', 'UACC_62_1',
       'UACC_62_2', 'UACC_62_3'],
      dtype='object', name='Sample Title')

In [11]:
# listing the column names
df.columns

Index(['Sample_geo_accession', 'Stage', 'cell type', 'sample_number',
       'cell_line', 'A1BG', 'A1CF', 'A2M', 'A2ML1', 'A2MP1',
       ...
       'BP-21201H5.1', 'BP-21264C1.1', 'BP-2168N6.1', 'BP-2168N6.3',
       'BP-2171C21.2', 'BP-2171C21.4', 'BP-2171C21.5', 'BP-2171C21.6',
       'BP-2189O9.2', 'YR211F11.2'],
      dtype='object', length=35243)

Data frames can also be sliced by rows without explicitly naming the row names or row numbers. Instead, we can slice by testing whether a condition is fulfilled or not:

In [12]:
# Finding out which rows match the stage: "primary melanocytes"
primary_indices = df.Stage == 'primary melanocytes'
print(primary_indices)

Sample Title
FM_1             True
FM_2             True
FM_3             True
SK_MEL_28_1     False
SK_MEL_28_2     False
SK_MEL_28_3     False
SK_MEL_147_1    False
SK_MEL_147_2    False
SK_MEL_147_3    False
UACC_62_1       False
UACC_62_2       False
UACC_62_3       False
Name: Stage, dtype: bool

In [13]:
# subsetting the rows based on this conditional set
primary_melanocytes_data = df[primary_indices]
primary_melanocytes_data

,Sample_geo_accession,Stage,cell type,sample_number,cell_line,...,BP-2171C21.4,BP-2171C21.5,BP-2171C21.6,BP-2189O9.2,YR211F11.2
Sample Title,,,,,,,,,,,
FM_1,GSM2344965,primary melanocytes,normal melanocytes,1,FM,...,0,0,6,2,0
FM_2,GSM2344966,primary melanocytes,normal melanocytes,2,FM,...,0,0,0,4,0
FM_3,GSM2344967,primary melanocytes,normal melanocytes,3,FM,...,1,0,6,3,1

In [19]:
# subsetting by conditionals in both rows and columns
primary_melanocytes_data2 = df.loc[df.Stage == 'primary melanocytes','cell_line']
primary_melanocytes_data2

Sample Title
FM_1    FM
FM_2    FM
FM_3    FM
Name: cell_line, dtype: object

You can driectly perform mathematical operations on numerical subsets of data frames:

In [ ]:
# adding the expression values in FM_2 and FM_3 for genes A1BG to A1CF
primary_melanocytes_data['A1BG'].iloc[1:3] + primary_melanocytes_data['A1CF'].iloc[1:3]

You can slice subsets of a data frame and convert back to a `numpy` ndarray or list by using:

*   `.to_numpy()` for ndarrays
*   `.tolist()` for lists.

In [ ]:
# using .to_numpy to convert the data in the column corresponding to the gene 'A1BG' in the primary_melanocytes_data data frame to a numpy array.

A1BGexpPrimary = primary_melanocytes_data['A1BG'].to_numpy()
print(A1BGexpPrimary)

You can also export dataframes back to Excel using the `.to_excel()` method.

In [ ]:
# exporting primary_melanocytes_data back to excel
primary_melanocytes_data.to_excel('primary_melanocytes_data.xlsx',index = False)

### <font color=brown> Practice </font>

1. Output the expression value for the gene 'A2M' of all of samples with Stage =  "metastatic"

In [ ]:
df.head()

### Additional Reading
[This website](https://pythonfordatascience.org/data-frames-python-pandas/), [this website](https://www.datacamp.com/community/tutorials/pandas-tutorial-dataframe-python), and [this website](https://www.tutorialspoint.com/python_pandas/python_pandas_dataframe.htm) give more information about pandas data frames.

### <font color=blue> Optional Bonus: Reshaping arrays

You can change the dimensions of the array using the .reshape() method, as long as the dimensions completely fit the number of elements in your array.

In [ ]:
print(array2)

In [ ]:
print(array2.reshape(4,2))

A vector (1D array):
$$\begin{bmatrix}
x_{11} \\
x_{21}
\end{bmatrix}$$

or

$$\begin{bmatrix}
x_{11} & x_{12}
\end{bmatrix}$$


A matrix (2D array):
$$\begin{bmatrix}
x_{11} & x_{12} \\
x_{21} & x_{22}
\end{bmatrix}$$

#### <font color=blue> Optional Bonus: Combining and Splitting arrays

For 1D and 2D arrays, the clearest way to concatenate arrays together is by using the `.hstack()` and `.vstack()` functions:

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

# concatenate along x-axis (by columns)
np.hstack([x, y])

In [ ]:
# concatenate along the second (y-) axis (by rows) (axes are also zero-indexed).
np.vstack([x, y])

For 1D and 2D arrays, splitting the arrays into smaller pieces can be most clearly done using the `np.vsplit()` and `np.hsplit()` functions:

In [ ]:
print(array2)

In [ ]:
splitV1,splitV2 = np.vsplit(array2,[1])

In [ ]:
print(splitV1)

In [ ]:
print(splitV2)

In [ ]:
splitH1,splitH2 = np.hsplit(array2,[3])

In [ ]:
print(splitH1)

In [ ]:
print(splitH2)