# Practice Problem Set 4 - KEY

Please note that the code here is just one way of getting the correct answer. Often, there are different ways to get to the same answer. If you have questions, please let us know.

In [1]:
# Import required libraries
import numpy as np
import pandas as pd
import scipy

In [2]:
# Setting some pandas preferences
pd.set_option('display.precision', 2)
pd.set_option('display.max_columns',10)

### Conditionals:

Triangles can be classified as: a) equilateral (all sides are equal), b) scalene (all sides are different), or c) isoscles (two sides are the same). Write a conditional statement to determine (and print out) which class a triangle falls under based on inputing the sides' lengths.   

Check your work by changing the lengths of the sides so that each class of triangle is tested.

In [3]:
a = 2
b = 2
c = 2
if a == b == c:
    print('This is an equilateral triangle')
elif a != b != c:
    print('This is a scalene triangle')
else:
    print('This is an isoscles triangle')

This is an equilateral triangle

### Iteration:

Make a list of eight numbers less than 10.

In [4]:
mylist = [1,2,3,4,5,6,7,8]

Use a for loop to print every other number in your list starting with the first number.

In [5]:
count = 1
for count in range(0,8,2):
    print(mylist[count])

1
3
5
7

Create a while loop that prints each number in your list until you reach a number greater than or equal to 5.

In [6]:
count = 0
while mylist[count] <=5:
    print(mylist[count])
    count += 1

1
2
3
4
5

### Iteration with Conditionals:

The random module in Python allows you to generate a list of random numbers.

In [7]:
# generating the random list
import random
randomlist = random.sample(range(0,30),10)
random_array = np.array(randomlist)
# sorting smallest to largest integer
random_array.sort()
print(random_array)

[ 0  6  7 13 14 20 23 24 26 29]

Create an iterative function that will print each number in the random_array UNLESS the number is greater than 20. If the loop stops before printing all of the numbers, print a message that states how many numbers less than or equal to 20 were in the array.

In [8]:
def whileElse(array):
    count = 0
    while count < 10:
        if random_array[count] <= 20:
            print('This number = ' + str(random_array[count]))
        else:
            print('Only ' + str(count) + ' numbers in the array are <= 20.')
            break
        count = count + 1

Now run your iterative function with the random array generated.

In [9]:
whileElse(random_array)

This number = 0
This number = 6
This number = 7
This number = 13
This number = 14
This number = 20
Only 6 numbers in the array are <= 20.

Let's try one more iterative function on our melanoma dataset.

In [ ]:
# A way to bring in Data
from google.colab import files
uploaded = files.upload()

In [10]:
# importing the melanoma dataset
melanoma_log2 = pd.read_excel('melanoma_zerosRemoved_log2transformed_2025.xlsx',index_col = 0)
melanoma_log2.head()

,Sample_geo_accession,Stage,cell type,sample_number,cell_line,...,ZYX,ZZEF1,ZZZ3,BP-21201H5.1,BP-2189O9.2
Sample Title,,,,,,,,,,,
FM_1,GSM2344965,primary melanocytes,normal melanocytes,1,FM,...,11.66,11.83,10.55,3.17,1.00
FM_2,GSM2344966,primary melanocytes,normal melanocytes,2,FM,...,11.63,11.54,11.06,2.81,2.00
FM_3,GSM2344967,primary melanocytes,normal melanocytes,3,FM,...,12.31,11.44,10.81,2.32,1.58
SK_MEL_28_1,GSM2344968,metastatic,melanoma cell line,4,SK_MEL_28,...,11.86,10.94,11.64,0.00,6.04
SK_MEL_28_2,GSM2344969,metastatic,melanoma cell line,5,SK_MEL_28,...,11.97,11.03,11.74,1.00,6.41

In [11]:
#calculate the group-by mean for each cell_line
mel_by_cell_mean = melanoma_log2.groupby('cell_line')
mel_by_cell_mean.head()

,Sample_geo_accession,Stage,cell type,sample_number,cell_line,...,ZYX,ZZEF1,ZZZ3,BP-21201H5.1,BP-2189O9.2
Sample Title,,,,,,,,,,,
FM_1,GSM2344965,primary melanocytes,normal melanocytes,1,FM,...,11.66,11.83,10.55,3.17,1.00
FM_2,GSM2344966,primary melanocytes,normal melanocytes,2,FM,...,11.63,11.54,11.06,2.81,2.00
FM_3,GSM2344967,primary melanocytes,normal melanocytes,3,FM,...,12.31,11.44,10.81,2.32,1.58
SK_MEL_28_1,GSM2344968,metastatic,melanoma cell line,4,SK_MEL_28,...,11.86,10.94,11.64,0.00,6.04
SK_MEL_28_2,GSM2344969,metastatic,melanoma cell line,5,SK_MEL_28,...,11.97,11.03,11.74,1.00,6.41
SK_MEL_28_3,GSM2344970,metastatic,melanoma cell line,6,SK_MEL_28,...,11.94,11.02,11.59,0.00,5.91
SK_MEL_147_1,GSM2344971,metastatic,melanoma cell line,7,SK_MEL_147,...,13.09,11.19,12.29,5.21,5.21
SK_MEL_147_2,GSM2344972,metastatic,melanoma cell line,8,SK_MEL_147,...,13.14,11.11,12.28,5.04,5.09
SK_MEL_147_3,GSM2344973,metastatic,melanoma cell line,9,SK_MEL_147,...,13.00,11.12,11.77,5.13,5.39
UACC_62_1,GSM2344974,metastatic,melanoma cell line,10,UACC_62,...,12.47,11.34,9.73,4.25,6.94
UACC_62_2,GSM2344975,metastatic,melanoma cell line,11,UACC_62,...,13.08,11.23,9.81,3.17,6.30
UACC_62_3,GSM2344976,metastatic,melanoma cell line,12,UACC_62,...,13.17,11.22,9.89,4.00,6.48

In [12]:
#calculate the group-by mean for each cell_line
mel_by_cell_mean = melanoma_log2.groupby('cell_line').mean(numeric_only=True)
mel_by_cell_mean.head()

,sample_number,A1BG,A2M,AAAS,AACS,...,ZYX,ZZEF1,ZZZ3,BP-21201H5.1,BP-2189O9.2
cell_line,,,,,,,,,,,
FM,2.0,8.63,14.79,10.53,11.07,...,11.87,11.60,10.80,2.77,1.53
SK_MEL_147,8.0,8.00,2.13,10.94,11.09,...,13.07,11.14,12.11,5.13,5.23
SK_MEL_28,5.0,8.49,11.42,10.86,10.65,...,11.92,11.00,11.66,0.33,6.12
UACC_62,11.0,8.82,13.87,11.12,10.75,...,12.91,11.26,9.81,3.81,6.57

Before we get to the iterative function, let's try to determine how many of the cell lines have a mean expression of less than 10 for the gene ZYX.

In [13]:
mean_exp = mel_by_cell_mean.loc[:,'ZYX']<10
print(mean_exp)
print(sum(mean_exp))

cell_line
FM            False
SK_MEL_147    False
SK_MEL_28     False
UACC_62       False
Name: ZYX, dtype: bool
0

Now let's say you're interested in looking at three different genes (AAAS, ARV1, ZZZ3). We want to create an iterative function that determines if any of the cell_lines have a mean expression count below ten for each gene in our list.

If they do, print that at least one cell line has a mean expression count <10 for the gene of interest (print the gene name). If they don't, then print that all of the cell lines have a mean expression count >= 10 for the gene of interest (print the gene name).

In [14]:
interest_genes = ["AAAS","ARV1","ZZZ3"]

for gene_count in range(0,3):
    if sum(mel_by_cell_mean.loc[:,interest_genes[gene_count]] < 10)<1:
        print('The mean expression count is >=10 for all cell lines for the gene: '
              + str(interest_genes[gene_count]))
    else:
        print('At least one cell line has a mean expression count <10 for the gene: '
              +str(interest_genes[gene_count]))
    gene_count += 1

The mean expression count is >=10 for all cell lines for the gene: AAAS
At least one cell line has a mean expression count <10 for the gene: ARV1
At least one cell line has a mean expression count <10 for the gene: ZZZ3