# Practice Problem Set 2

For practice creating and manipulating lists, arrays, and data frames, perform the following tasks.

In [ ]:
# Makes it so any variable or statement on it's own line gets printed w/o print()
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
pip install scipy

Defaulting to user installation because normal site-packages is not writeable
Collecting scipy
  Downloading scipy-1.13.1-cp39-cp39-macosx_12_0_arm64.whl (30.3 MB)
     |████████████████████████████████| 30.3 MB 17.2 MB/s eta 0:00:01
Requirement already satisfied: numpy<2.3,>=1.22.4 in /Users/erinbarnett/Library/Python/3.9/lib/python/site-packages (from scipy) (2.0.2)
Installing collected packages: scipy
Successfully installed scipy-1.13.1
WARNING: You are using pip version 21.2.4; however, version 25.0.1 is available.
You should consider upgrading via the '/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# Import required libraries
import numpy as np
import pandas as pd
import scipy

In [ ]:
# Setting some pandas preferences
pd.set_option('precision', 2)
pd.set_option('max_columns',10)

## Manipulating Lists
Create a list, called "mylist", of five elements of your choosing.

In [ ]:
mylist = [1,5,10,15,18]

Slice out the third element.

In [ ]:
mylist[2] #or mylist[-3]

10

Add a 6 to the end of your list.

In [ ]:
mylist.append(6)
mylist

[1, 5, 10, 15, 18, 6]

Add a 24 to the third position in your list.

In [ ]:
mylist.insert(2,24)
mylist

[1, 5, 24, 10, 15, 18, 6]

Slice out the last three elements of your list.

In [ ]:
mylist[-3:]

[15, 18, 6]

Add "yes" and "no" to the end of your list.

In [ ]:
mylist.extend(['yes','no'])
mylist

[1, 5, 24, 10, 15, 18, 6, 'yes', 'no']

Remove the 24 and the change "yes" and "no" to 0 and 1.

In [ ]:
mylist.remove(24)
mylist[-2:]=[0,1]
mylist

[1, 5, 10, 15, 18, 6, 0, 1]

Create a new list of at least two elements. Stitch your new list to your first list (mylist) and name it mixedlist.

In [ ]:
newlist = [True,False]
mixedlist = mylist + newlist
mixedlist

[1, 5, 10, 15, 18, 6, 0, 1, True, False]

Determine how long your list is.

In [ ]:
len(mixedlist)

10

Copy the first four values of the mixedlist and then remove the middle two elements.

In [ ]:
mixedsubset = mixedlist[:4].copy()
mixedsubset
del(mixedsubset[1:3])
mixedsubset

[1, 5, 10, 15]

[1, 15]

## Manipulating Arrays & Data Frames

In [ ]:
array1 = np.array([[5,6,7,8],[9,10,11,12]])
array1

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Multipy the entire array by 3.

In [ ]:
array1*3

array([[15, 18, 21, 24],
       [27, 30, 33, 36]])

Extract the third element of each row.

In [ ]:
array1[:,2]

array([ 7, 11])

Change the dimensions of the array into a singular column.

In [ ]:
array1.reshape(8,1)

array([[ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

Create two arrays, x and y, with four elements each. Concatenate them along x-axis (by columns).

In [ ]:
x = np.array([4,12,13,15])
y = np.array([-5,30,2,199])
np.hstack([x,y])

array([  4,  12,  13,  15,  -5,  30,   2, 199])

Concatenate x and y along y-axis (by rows) and save as z.

In [ ]:
z = np.vstack([x,y])
z

array([[  4,  12,  13,  15],
       [ -5,  30,   2, 199]])

Output the middle two elements of the second row of z.

In [ ]:
z[1,1:3]

array([30,  2])

Split the z array into two 2x2 arrays.

In [ ]:
splitH1,splitH2 = np.hsplit(z,[2])
splitH1
splitH2

array([[ 4, 12],
       [-5, 30]])

array([[ 13,  15],
       [  2, 199]])

#### For the next several practice steps, you will need `GSE88741_meta.csv`. Please download from Canvas before beginning this section.

In [ ]:
# Bring in metadata from Excel. You should pick the index column as the column with the most representative sample identifier
meta = pd.read_csv("/Users/erinbarnett/OneDrive - Fred Hutchinson Cancer Center/PABIO/PABIO_536_TA/GSE88741_meta.csv", index_col=0)
meta
data = pd.read_csv("/Users/erinbarnett/OneDrive - Fred Hutchinson Cancer Center/PABIO/PABIO_536_TA/GSE88741-expression-B.csv")
data

,Sample_geo_accession,Stage,CellType,CellLine
SampleTitle,,,,
FM_1,GSM2344965,primary melanocytes,normal melanocytes,FM
FM_2,GSM2344966,primary melanocytes,normal melanocytes,FM
FM_3,GSM2344967,primary melanocytes,normal melanocytes,FM
SK_MEL_28_1,GSM2344968,metastatic,melanoma cell line,SK_MEL_28
SK_MEL_28_2,GSM2344969,metastatic,melanoma cell line,SK_MEL_28
SK_MEL_28_3,GSM2344970,metastatic,melanoma cell line,SK_MEL_28
SK_MEL_147_1,GSM2344971,metastatic,melanoma cell line,SK_MEL_147
SK_MEL_147_2,GSM2344972,metastatic,melanoma cell line,SK_MEL_147
SK_MEL_147_3,GSM2344973,metastatic,melanoma cell line,SK_MEL_147
UACC_62_1,GSM2344974,metastatic,melanoma cell line,UACC_62
UACC_62_2,GSM2344975,metastatic,melanoma cell line,UACC_62
UACC_62_3,GSM2344976,metastatic,melanoma cell line,UACC_62

,gene_symbol,GSM2344965,GSM2344966,GSM2344967,GSM2344968,GSM2344969,GSM2344970,GSM2344971,GSM2344972,GSM2344973,GSM2344974,GSM2344975,GSM2344976
0,A1BG,400,320,490,331,363,390,225,248,301,755,391,310
1,A1CF,1,1,3,0,0,1,0,2,3,1,0,5
2,A2M,23278,47606,20484,2652,2707,2854,4,7,3,26726,10394,12096
3,A2ML1,6,8,10,1,7,4,3,0,1,8,4,7
4,A2MP1,21,7,34,0,6,3,0,0,0,13,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
35233,BP-2171C21.4,0,0,1,3,0,0,0,0,0,0,0,4
35234,BP-2171C21.5,0,0,0,0,2,0,0,0,0,0,0,0
35235,BP-2171C21.6,6,0,6,15,21,14,5,6,9,46,25,22
35236,BP-2189O9.2,2,4,3,66,85,60,37,34,42,123,79,89
35237,YR211F11.2,0,0,1,0,0,1,0,2,0,0,1,0

Subset the data frame to show the first four samples and all of their data.

In [ ]:
meta.shape

(12, 4)

In [ ]:
meta.iloc[:4,0:]

,SampleTitle,Stage,CellType,CellLine
Sample_geo_accession,,,,
GSM2344965,FM_1,primary melanocytes,normal melanocytes,FM
GSM2344966,FM_2,primary melanocytes,normal melanocytes,FM
GSM2344967,FM_3,primary melanocytes,normal melanocytes,FM
GSM2344968,SK_MEL_28_1,metastatic,melanoma cell line,SK_MEL_28

Extract data in "cell type" for "FM_3", "SK_MEL_28_3", and "UACC_62_3".

In [ ]:
meta.loc[['FM_3','SK_MEL_28_3','UACC_62_3'],'CellType']

SampleTitle
FM_3           normal melanocytes
SK_MEL_28_3    melanoma cell line
UACC_62_3      melanoma cell line
Name: CellType, dtype: object

Output the Sample_geo_accession numbers of all the samples with cell type = "normal melanocytes".

In [ ]:
sample_meta = meta.iloc[:,0]
sample_meta

SampleTitle
FM_1            GSM2344965
FM_2            GSM2344966
FM_3            GSM2344967
SK_MEL_28_1     GSM2344968
SK_MEL_28_2     GSM2344969
SK_MEL_28_3     GSM2344970
SK_MEL_147_1    GSM2344971
SK_MEL_147_2    GSM2344972
SK_MEL_147_3    GSM2344973
UACC_62_1       GSM2344974
UACC_62_2       GSM2344975
UACC_62_3       GSM2344976
Name: Sample_geo_accession, dtype: object

In [ ]:
normal_indices = meta.iloc[:,2] == 'normal melanocytes'
normal_indices
sample_meta = meta.iloc[:,0:1]
normal_data = sample_meta[normal_indices]
normal_data

SampleTitle
FM_1             True
FM_2             True
FM_3             True
SK_MEL_28_1     False
SK_MEL_28_2     False
SK_MEL_28_3     False
SK_MEL_147_1    False
SK_MEL_147_2    False
SK_MEL_147_3    False
UACC_62_1       False
UACC_62_2       False
UACC_62_3       False
Name: CellType, dtype: bool

            Sample_geo_accession
SampleTitle
FM_1                  GSM2344965
FM_2                  GSM2344966
FM_3                  GSM2344967